# Generated by Django 3.2.2 on 2021-05-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotrequest',
            name='verify_mail_sent',
        ),
    ]
